pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('firstTask') {
                    bat "docker build -t flask-app:${BUILD_NUMBER} ."
                }
            }
        }

        stage('Test') {
            steps {
                bat 'echo Running basic tests...'
            }
        }

        stage('Deploy to Staging') {
            when {
                branch 'develop'
            }
            steps {
                bat 'echo Deploying to staging environment'
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}